config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/create'
  devise_for :users
  resources:post_bikes,only:[:new,:create,:show,:index,:edit] do
    resources:post_bike_comments,only:[:create,:destroy]
    resource:favorites,only:[:create,:destroy]
  end
  resources:users,only:[:show,:index,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    resource:room_users,only:[:create] do
     resource:chats,only:[:create,:show]
    end
  end
  get 'searches/search',as:"search"
  root to: 'homes#home'
  get 'homes/about',as:"about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:post_bike
end

app/models/post_bike.rb
class PostBike < ApplicationRecord
  is_impressionable counter_cache: true
  belongs_to:user
  has_many:post_tags,dependent: :destroy
  has_many:tags,through: :post_tags

  has_many:post_bike_comments,dependent: :destroy

  has_many:favorites,dependent: :destroy
  has_many:likes,through: :favorites,source: :user

  has_one_attached:bike_image

  def get_bike_image(width,height)
    unless bike_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      bike_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      bike_image.variant(resize_to_limit:[width,height]).processed
  end
  def get_maker(number)
    maker=["ホンダ","スズキ","ヤマハ","KTM","ハーレー"]
    maker[number]
  end
  def get_engine(number)
    engine=["~50cc","50~125cc","125~250cc","250~400cc","400cc~"]
    engine[number]
  end
end

app/models/post_bike_comment.rb
class PostBikeComment < ApplicationRecord
  belongs_to:user
  belongs_to:post_bike
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to:post_bike
  belongs_to:tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follow,class_name: "User"
  belongs_to:followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many:room_users,dependent: :destroy
  has_many:chats,dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many:post_tags,dependent: :destroy
  has_many:post_bikes,through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached:profile_image
  has_many:post_bikes,dependent: :destroy
  has_many:post_bike_comments,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:follow,class_name: "Relationship",foreign_key: "followed_id" ,dependent: :destroy
  has_many:followed,class_name: "Relationship" ,foreign_key: "follow_id" ,dependent: :destroy
  # その人がフォローした人達一覧
  has_many:followeds,through: :follow,source: :follow
  # その人がフォローされた人達一覧
  has_many:follows,through: :followed,source: :followed

  has_many:room_users,dependent: :destroy
  has_many:rooms,through: :room_users
  has_many:chats,dependent: :destroy

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no-image-icon.jpg")
      profile_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      profile_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    # 相手のUserのID取得
    @user = User.find(params[:user_id])
    # 相手のUSERが所属しているROOMを取得
    you_room = @user.rooms
    # 相手のUSERが所属しているROOMを取得
    my_room = current_user.rooms
    # 重複している値を取得
    room = you_room & my_room
    room.each do |f|
     @room=f
    end
    @chat = Chat.new
  end

  def create
    user = User.find(params[:user_id])
    # 相手のUSERが所属しているROOMを取得
    you_room = user.rooms
    # 相手のUSERが所属しているROOMを取得
    my_room = current_user.rooms
    # 重複している値(配列)を取得(一件だけ取得する)
    room = you_room & my_room

    room.each do |n|
      @room = n
    end

    chat = Chat.new(chat_params)
    chat.user_id = current_user.id
    chat.room_id = @room.id
    chat.save
    redirect_to user_room_users_chats_path(user.id)
  end
  def chat_params
    params.require(:chat).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # 今日の投稿したものを範囲で取得
    @today_user_post = @user.post_bikes.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day)
     # 昨日の投稿したものを範囲で取得
    @yesterday_user_post = @user.post_bikes.where(created_at: Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day)

    if @today_user_post.count == 0 || @yesterday_user_post.count == 0
      @ratio = "比較不可"
    else
      @ratio = (@today_user_post.count / @yesterday_user_post.count) * 100
    end
    # 今週の合計を配列で取得
    @week_post_bike = @user.post_bikes.where(created_at: 1.week.ago..Time.zone.now)
     # 先週の合計を配列で取得
    @weeks_post_bike = @user.post_bikes.where(created_at: 2.week.ago..1.week.ago)

    if @week_post_bike.count == 0 || @weeks_post_bike.count == 0
      @ratios = "比較不可"
    else
      @ratios = (@week_post_bike.count / @weeks_post_bike.count) * 100
    end
    # 一週間前までの投稿を日にち毎に配列で取得
    @week_today = @user.post_bikes.where(created_at: Time.zone.now.all_day).count
    @week_yesterday = @user.post_bikes.where(created_at: Time.zone.yesterday.all_day).count
    @week_2day = @user.post_bikes.where(created_at: Time.zone.now.ago(2.days).all_day).count
    @week_3day = @user.post_bikes.where(created_at: Time.zone.now.ago(3.days).all_day).count
    @week_4day = @user.post_bikes.where(created_at: Time.zone.now.ago(4.days).all_day).count
    @week_5day = @user.post_bikes.where(created_at: Time.zone.now.ago(5.days).all_day).count
    @week_6day = @user.post_bikes.where(created_at: Time.zone.now.ago(6.days).all_day).count

  end
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_bikes_helper.rb
module PostBikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<div class="container">
  <h1>チャット</h1>
  <table class="table">
  <% @room.chats.each do |chat| %>
　　  <tr>
　　    <td><%= image_tag chat.user.get_profile_image(50,50) %></td>
　　    <td><%= chat.comment %></td>
　　  </tr>
  <% end %>
  </table>
  <h1>コメント</h1>
  <%= form_with model: @chat,url: user_room_users_chats_path(@user.id) do |f| %>
    <%= f.text_area :comment,class:"form-control" %>
    <%= f.submit"送信" %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <%= form_with model: @user do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name,class:"form-control" %><br>
    <%= f.label :introduction %><br>
    <%= f.text_area :introduction,rows: 5,placeholder:"自己紹介はここに",class:"form-control" %><br>
    <labe>画像</labe><br>
    <%= f.file_field :profile_image,accept:"image/jpg" %><br>
    <%= f.submit"変更" %><br>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>USER INDEX</h1>
  <table class="table">
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td>
        NAME：
        <%= link_to user_path(user.id) do %>
          <%= user.name %>
        <% end %>
      </td>
      <td>INTRODUCTION：<%= user.introduction %></td>
      <td>
      <% unless user == current_user %>
        <% if user.follows.exists?(id: current_user.id) %>
          <%= link_to user_relationships_path(user.id),method: :delete,class:"btn btn-danger" do %>
            解除
          <% end %>
        <% else %>
          <%= link_to user_relationships_path(user.id),method: :post,class:"btn btn-success" do %>
            フォロー
          <% end %>
        <% end %>
      <% end %>
      </td>
      <td>
        フォロー<%= user.followeds.count %>人<br>
        フォロワー<%= user.follows.count %>人
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div>
    <h1>USER SHOW</h1>
    <%= image_tag @user.get_profile_image(200,200) %>
    <p>NAME:<%= @user.name %></p>
    <P>INTRODUCTION:<%= @user.introduction %></P>
    <% if @user == current_user %>
      <%= link_to"EDIT",edit_user_path(@user.id),class:"btn btn-success" %>
    <% end %>
    <% if current_user.followeds.exists?(id: @user.id) and @user.followeds.exists?(id: current_user.id) %>
      <% unless @user == current_user %>
        <%= link_to"DM",user_room_users_path(@user.id),method: :post,class:"btn btn-success" %>
      <% end %>
    <% end %>
  </div>
  <div>
    投稿履歴
    <table class="table">
      <tr>
        <td>今日</td>
        <td>昨日</td>
        <td>比率</td>
        <td>今週</td>
        <td>先週</td>
        <td>比率</td>
      </tr>
      <tr>
        <td><%= @today_user_post.count %>件</td>
        <td><%= @yesterday_user_post.count %>件</td>
        <td><%= @ratio %></td>
        <td><%= @week_post_bike.count %></td>
        <td><%= @weeks_post_bike.count %></td>
        <td><%= @ratios %></td>
      </tr>
    </table>
    <table class="table">
      <tr>
        <td>今日</td>
        <td>昨日</td>
        <td>２日毎</td>
        <td>３日前</td>
        <td>４日前</td>
        <td>５日前</td>
        <td>６日前</td>
      </tr>
      <tr>
        <td><%= @week_today %></td>
        <td><%= @week_yesterday %></td>
        <td><%= @week_2day %></td>
        <td><%= @week_3day %></td>
        <td><%= @week_4day %></td>
        <td><%= @week_5day %></td>
        <td><%= @week_6day %></td>
      </tr>
    </table>

    <canvas id="myChart"></canvas>
　　<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

　　<script>
  　$(document).on('turbolinks:load', function () {
　　var ctx = document.getElementById('myChart');
　  　var myChart = new Chart(ctx, {
　　    type: 'line',
    　　data: {
        　　labels: ['今日', '1日前', '2日前', '3日前', '4日前', '5日前','6日前'],
          　　datasets: [{
            　　label: '投稿離席',
            　　data: [<%= @week_today %>, <%= @week_yesterday %>, <%= @week_2day %>, <%= @week_3day %>, <%= @week_4day %>,<%= @week_5day %>,<%= @week_6day %> ],
  　　 　　         backgroundColor: [
           　　     'rgba(255, 99, 132, 0.2)'
          　　  ],
            　　borderColor: [
        　　        'rgba(255, 99, 132, 1)'
    　　        ],
        　　　　    borderWidth: 3
      　 　 }]
   　　 },
   　    options: {
   　　　　     y: {
   　　　 　       min: 0,
               max: 10,
            },
        },
　  　});
　  });
　</script>


  </div>
  <div>
    <h1>BIKES</h1>
    <table>
      <% @user.post_bikes.each do |bike| %>
        <tr>
          <td><%= image_tag bike.get_bike_image(100,100) %></td>
          <td><%= bike.name %></td>
          <td><%= bike.opinion %></td>
          <td><%= bike.get_engine(bike.engine) %></td>
          <td><%= bike.get_maker(bike.maker) %></td>
        </tr>
      <% end %>
    </table>
  </div>


</div>