config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/create'
  devise_for :users
  resources:post_bikes,only:[:new,:create,:show,:index,:edit] do
    resources:post_bike_comments,only:[:create,:destroy]
    resource:favorites,only:[:create,:destroy]
  end
  resources:users,only:[:show,:index,:edit,:update] do
    resource:relationships,only:[:create,:destroy]
    resource:room_users,only:[:create] do
     resource:chats,only:[:create,:show]
    end
  end
  get 'searches/search',as:"search"
  root to: 'homes#home'
  get 'homes/about',as:"about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:post_bike
end

app/models/post_bike.rb
class PostBike < ApplicationRecord
  is_impressionable counter_cache: true
  belongs_to:user
  has_many:post_tags,dependent: :destroy
  has_many:tags,through: :post_tags

  has_many:post_bike_comments,dependent: :destroy

  has_many:favorites,dependent: :destroy
  has_many:likes,through: :favorites,source: :user

  has_one_attached:bike_image

  def get_bike_image(width,height)
    unless bike_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      bike_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      bike_image.variant(resize_to_limit:[width,height]).processed
  end
  def get_maker(number)
    maker=["ホンダ","スズキ","ヤマハ","KTM","ハーレー"]
    maker[number]
  end
  def get_engine(number)
    engine=["~50cc","50~125cc","125~250cc","250~400cc","400cc~"]
    engine[number]
  end
end

app/models/post_bike_comment.rb
class PostBikeComment < ApplicationRecord
  belongs_to:user
  belongs_to:post_bike
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to:post_bike
  belongs_to:tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follow,class_name: "User"
  belongs_to:followed,class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many:room_users,dependent: :destroy
  has_many:chats,dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to:user
  belongs_to:room
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many:post_tags,dependent: :destroy
  has_many:post_bikes,through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached:profile_image
  has_many:post_bikes,dependent: :destroy
  has_many:post_bike_comments,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:follow,class_name: "Relationship",foreign_key: "followed_id" ,dependent: :destroy
  has_many:followed,class_name: "Relationship" ,foreign_key: "follow_id" ,dependent: :destroy
  # その人がフォローした人達一覧
  has_many:followeds,through: :follow,source: :follow
  # その人がフォローされた人達一覧
  has_many:follows,through: :followed,source: :followed

  has_many:room_users,dependent: :destroy
  has_many:rooms,through: :room_users
  has_many:chats,dependent: :destroy

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no-image-icon.jpg")
      profile_image.attach(io:File.open(file_path),filename:"default-image.jpg",content_type:"image/jpg")
    end
      profile_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    # 相手のUserのID取得
    @user = User.find(params[:user_id])
    # 相手のUSERが所属しているROOMを取得
    you_room = @user.rooms
    # 相手のUSERが所属しているROOMを取得
    my_room = current_user.rooms
    # 重複している値を取得
    room = you_room & my_room
    room.each do |f|
     @room=f
    end
    @chat = Chat.new
  end

  def create
    user = User.find(params[:user_id])
    # 相手のUSERが所属しているROOMを取得
    you_room = user.rooms
    # 相手のUSERが所属しているROOMを取得
    my_room = current_user.rooms
    # 重複している値(配列)を取得(一件だけ取得する)
    room = you_room & my_room

    room.each do |n|
      @room = n
    end

    chat = Chat.new(chat_params)
    chat.user_id = current_user.id
    chat.room_id = @room.id
    chat.save
    redirect_to user_room_users_chats_path(user.id)
  end
  def chat_params
    params.require(:chat).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/post_bikes_controller.rb
class PostBikesController < ApplicationController
  def new
    # @post_bike = PostBike.new
  end
  def create
    @post_bike = PostBike.new(name: params[:name],opinion: params[:opinion],engine: params[:engine],maker: params[:maker])
    @post_bike.user_id = current_user.id
    @post_bike.save
    # フォームから送られてきたtag_nameを取得し、配列に変換
    tag = params[:tag_name].split(",")
    #　Tagのデータベースから、:tag_nameの値を全て取得し配列とする
    old_tag = Tag.pluck(:tag_name)
    # 上記二つを取得し、差し引いてやる（保存済みの名前はここで除去する）
    new_tag = tag - old_tag
    # 新規タグの保存
    new_tag.each do |n|
      Tag.create(tag_name: n)
    end

    tag.each do |n|
      tag = Tag.find_by(tag_name: n)
      PostTag.create(post_bike_id: @post_bike.id,tag_id: tag.id)
    end
    redirect_to users_path
  end

  def show
    @post_bike = PostBike.find(params[:id])
    impressionist(@post_bike,nil,unique: [:ip_address])
    @post_bike_comment = PostBikeComment.new
  end

  def index
    to = Time.current
    from = (to -6.day)
    tab = params[:key]
    # indexのタグ一覧から飛んできた場合
    if tab.blank?
      @post_bikes = PostBike.all
      @post_bikes = PostBike.includes(:likes).sort{|b,a|a.likes.size <=>b.likes.size}
      @tags = Tag.all
    else
      @post_bikes = Tag.find_by(id: tab.to_i).post_bikes
      @tags = Tag.all
    end
    def edit
      @post_bike = PostBike.find(params[:id])
    end
    @rank_post_bikes = PostBike.order(impressions_count: 'DESC') # ソート機能を追加
  end
  private
  def post_bike_params
    params.require(:post_bike).permit(:name,:opinion,:engine,:maker)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # 今日の投稿したものを範囲で取得
    @today_user_post = @user.post_bikes.where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day)
     # 昨日の投稿したものを範囲で取得
    @yesterday_user_post = @user.post_bikes.where(created_at: Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day)

    if @today_user_post.count == 0 || @yesterday_user_post.count == 0
      @ratio = "比較不可"
    else
      @ratio = (@today_user_post.count / @yesterday_user_post.count) * 100
    end
    # 今週の合計を配列で取得
    @week_post_bike = @user.post_bikes.where(created_at: 1.week.ago..Time.zone.now)
     # 先週の合計を配列で取得
    @weeks_post_bike = @user.post_bikes.where(created_at: 2.week.ago..1.week.ago)

    if @week_post_bike.count == 0 || @weeks_post_bike.count == 0
      @ratios = "比較不可"
    else
      @ratios = (@week_post_bike.count / @weeks_post_bike.count) * 100
    end
    # 一週間前までの投稿を日にち毎に配列で取得
    @week_today = @user.post_bikes.where(created_at: Time.zone.now.all_day).count
    @week_yesterday = @user.post_bikes.where(created_at: Time.zone.yesterday.all_day).count
    @week_2day = @user.post_bikes.where(created_at: Time.zone.now.ago(2.days).all_day).count
    @week_3day = @user.post_bikes.where(created_at: Time.zone.now.ago(3.days).all_day).count
    @week_4day = @user.post_bikes.where(created_at: Time.zone.now.ago(4.days).all_day).count
    @week_5day = @user.post_bikes.where(created_at: Time.zone.now.ago(5.days).all_day).count
    @week_6day = @user.post_bikes.where(created_at: Time.zone.now.ago(6.days).all_day).count

  end
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_bikes_helper.rb
module PostBikesHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/post_bikes/edit.html.erb
<div class="container">
  <%= form_with model: @post_bike do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name,class:"form-control" %>
    <%= f.label :opinion %>
    <%= f.text_area :opinion,class:"form-control",rows: 4 %>
    <label>排気量</label><br>
    <%= f.select :engine,{"~50cc"=>0,"50~125cc"=>1,"125~250cc"=>2,"250~400cc"=>3,"400cc~"=>4} %><br>
    <label>メーカー</label><br>
    <%= f.select :maker,{"ホンダ"=>0,"スズキ"=>1,"ヤマハ"=>2,"KTM"=>3,"ハーレー"=>4,} %><br>
    <label>タグ</label>
    <%= f.text_field :tag_name,placeholder:"複数の場合は,区切りで",class:"form-control" %>
    <label>画像</label><br>
    <%= f.file_field :bike_image,accept:"image/jpg" %><br>
    <%= f.submit"送信" %>
  <% end %>
</div>

app/views/post_bikes/index.html.erb
<div class="container">
  <%= form_with url: search_path,method: :get do |f| %>
    <%= f.select :model,{"User"=>"User","Bike"=>"Bike"},include_blank: true %>
    <%= f.search_field :content %>
    <%= f.submit"検索" %>
  <% end %>


  <% @tags.each do |tag| %>
    <%= link_to post_bikes_path(key: tag) do %>
      <%= tag.tag_name %>
    <% end %>
  <% end %>
  <table class="table">
    <% @post_bikes.each do |post_bike| %>
      <tr>
        <td><%= image_tag post_bike.get_bike_image(150,150) %></td>
        <td>
          <%= link_to post_bike_path(post_bike.id) do %>
            <%= post_bike.name %>
          <% end %>
        </td>
        <td><%= post_bike.opinion %></td>
        <td><%= post_bike.get_maker(post_bike.maker) %></td>
        <td><%= post_bike.get_engine(post_bike.engine) %></td>
        <td>
          <% if post_bike.likes.exists?(id: current_user.id) %>
            <%= link_to post_bike_favorites_path(post_bike.id),method: :delete do %>
              💖いいね<%= post_bike.likes.count %>件
            <% end %>
          <% else %>
            <%= link_to post_bike_favorites_path(post_bike.id),method: :post do %>
              💛いいね<%= post_bike.likes.count %>件
            <% end %>
          <% end %>
        </td>
        <td><%= post_bike.impressions_count %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/post_bikes/new.html.erb
<div class="container">
  <h1>PostBikes#new</h1>

  <%= form_with url: post_bikes_path,method: :post do |f| %>
    <label for="name">NAME</label><br>
    <%= f.text_field :name,id:"name",placeholder:"名前はここに",class:"form-control" %><br>
    <label for="opinion">OPINION</label><br>
    <%= f.text_area :opinion,id:"opinion",rows: 5,placeholder:"説明はここに",class:"form-control" %><br>
    <label>排気量</label><br>
    <%= f.select :engine,{"~50cc"=>0,"50~125cc"=>1,"125~250cc"=>2,"250~400cc"=>3,"400cc~"=>4} %><br>
    <label>メーカー</label><br>
    <%= f.select :maker,{"ホンダ"=>0,"スズキ"=>1,"ヤマハ"=>2,"KTM"=>3,"ハーレー"=>4,} %><br>
    <label>タグ</label>
    <%= f.text_field :tag_name,placeholder:"複数の場合は,区切りで",class:"form-control" %>
    <%= f.submit"送信" %>

<% end %>
</div>

app/views/post_bikes/show.html.erb
<div class="container">
  <table class="table">
    <tr>
      <td><%= image_tag @post_bike.get_bike_image(200,200) %></td>
    </tr>
    <tr>
      <td> <%= @post_bike.name %></td>
      <td><%= @post_bike.opinion %></td>
      <td><%= @post_bike.get_engine(@post_bike.engine) %></td>
      <td> <%= @post_bike.get_maker(@post_bike.maker) %></td>
      <td>
        <% @post_bike.tags.each do |tag| %>
          <%= tag.tag_name %><br>
        <% end %>
      </td>
      <% if @post_bike.user == current_user %>
        <td><%= link_to"EDIT",edit_post_bike_path(@post_bike.id) %></td>
      <% end %>
    </tr>
  </table>

  <h2>COMMENT</h2>
  <!--コメント一覧-->
  <table class="table">
    <% @post_bike.post_bike_comments.each do |comment| %>
    <tr>
      <td><%= image_tag comment.user.get_profile_image(60,60) %></td>
      <td><%= comment.comment %></td>
    </tr>
    <% end %>
  </table>

  <!--コメント投稿フォーム-->
  <%= form_with model: @post_bike_comment,url:  post_bike_post_bike_comments_path(@post_bike.id) do |f| %>
    <%= f.text_area :comment,placeholder:"コメントはここに",rows: 4,class:"form-control" %>
    <%= f.submit"送信" %>
  <% end %>
  <%=  @post_bike.impressionist_count %>
</div>